apiVersion: v1
kind: ConfigMap
metadata:
  name: sample-installer-config
  namespace: node-installer
data:
  install.sh: |
    #!/bin/bash

    # Create a test file
    touch test1.txt
    sleep 5
    while true; do sleep 100000; done